services:
  backend:
    build: ./docker/backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - .env
  postgres:
    image: postgres:16.2
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres:
