development:
  dialect: postgres
  datasource: host=${POSTGRES_CONTAINER_NAME} port=${POSTGRES_PORT} dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} sslmode=disable
  dir: ./database/migrations
